### ISSUE TITLE
es6 support? 

### ISSUE THREAD

**Issue by rootical** [angular/dgeni#122]
After searching and trying, I can't start using dgeni on one of my es6 based projects.
I am getting a JavaScript error ``"Unexpected reserved word"`` which links to ``import`` reserved keyword.

I can only see a branch called es6 which is 11 months old. Are there any plans for es6 syntax support, when it could happen? Maybe there's a way I could start using dgeni now like pointing to polyfilled version of application or whatever?

Thanks for your great work.

**Comment by hco** [comment]
:+1:

**Comment by greaterweb** [comment]
I'm also looking for a solution for this. 

Do any of the contributors have any input to lend?

**Comment by heff** [comment]
:+1:

**Comment by daniele-zurico** [comment]
Any news...I've the same problem.

**Comment by petebacondarwin** [comment]
I am going to try updating to use espree rather than esprima.

**Comment by daniele-zurico** [comment]
great news!! we will wait your news ;)

**Comment by olegskl** [comment]
Any news on this?

**Comment by petebacondarwin** [comment]
Here we go: https://github.com/angular/dgeni-packages/pull/130

If this looks OK to everyone I will merge and publish a new version later today

**Comment by karol-f** [comment]
Hi, using "angular/dgeni-packages#espree-refact" in package.json and running geni on some JS files with es6 got me this:

```javascript
error:   Error: Unknown node type ExportDefaultDeclaration.
    at Controller.traverse (/Users/Karol/www/os/dgeni/dgeni-example-master/node_modules/dgeni-packages/node_modules/estraverse/estraverse.js:517:31)
    at traverse (/Users/Karol/www/os/dgeni/dgeni-example-master/node_modules/dgeni-packages/node_modules/estraverse/estraverse.js:709:27)
    at findNodeAfter (/Users/Karol/www/os/dgeni/dgeni-example-master/node_modules/dgeni-packages/jsdoc/processors/extractJSDocComments.js:82:3)
    at /Users/Karol/www/os/dgeni/dgeni-example-master/node_modules/dgeni-packages/jsdoc/processors/extractJSDocComments.js:57:32
    at Function.forEach (/Users/Karol/www/os/dgeni/dgeni-example-master/node_modules/dgeni-packages/node_modules/lodash/dist/lodash.js:3298:15)
    at /Users/Karol/www/os/dgeni/dgeni-example-master/node_modules/dgeni-packages/jsdoc/processors/extractJSDocComments.js:47:11
    at Function.filter (/Users/Karol/www/os/dgeni/dgeni-example-master/node_modules/dgeni-packages/node_modules/lodash/dist/lodash.js:3151:15)
    at Object.$process (/Users/Karol/www/os/dgeni/dgeni-example-master/node_modules/dgeni-packages/jsdoc/processors/extractJSDocComments.js:40:16)
    at /Users/Karol/www/os/dgeni/dgeni-example-master/node_modules/dgeni/lib/Dgeni.js:202:28
    at _fulfilled (/Users/Karol/www/os/dgeni/dgeni-example-master/node_modules/dgeni/node_modules/q/q.js:798:54)
```

I've checked it using https://github.com/petebacondarwin/dgeni-example and changing to "angular/dgeni-packages#espree-refact" in package.json. Also adding bunch of es6 files with "class" and "import".

**Comment by matthiasg** [comment]
we are using a few features from es7 in our projects (via babel) such as  `['es7.asyncFunctions', 'es7.objectRestSpread', 'es7.decorators']` will this be supported (e.g ignored, doesnt have to flow into documentation) similar to [esdoc](https://www.npmjs.com/package/esdoc) ?

**Comment by NickHeiner** [comment]
For future people who find this issue: I worked around this by using babel to transform my code before feeding it in to dgeni.
