### ISSUE TITLE
dgeni is currently broken

### ISSUE THREAD

**Issue by r1chardj0n3s** [angular/dgeni#148]
Currently all usages of dgeni result in the following:

```bash
error:   Error processing docs:  TypeError: object is not a function
    at Function.v.extend.async (/private/tmp/merde/dgeni-example/node_modules/dgeni/node_modules/validate.js/validate.js:196:14)
    at /private/tmp/merde/dgeni-example/node_modules/dgeni/lib/Dgeni.js:166:23
    at _fulfilled (/private/tmp/merde/dgeni-example/node_modules/dgeni/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/private/tmp/merde/dgeni-example/node_modules/dgeni/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/private/tmp/merde/dgeni-example/node_modules/dgeni/node_modules/q/q.js:796:13)
    at /private/tmp/merde/dgeni-example/node_modules/dgeni/node_modules/q/q.js:857:14
    at runSingle (/private/tmp/merde/dgeni-example/node_modules/dgeni/node_modules/q/q.js:137:13)
    at flush (/private/tmp/merde/dgeni-example/node_modules/dgeni/node_modules/q/q.js:125:13)
    at process._tickCallback (node.js:415:13)
    at Function.Module.runMain (module.js:499:11)
```

A number of attempts were used to get dgeni working, including starting from scratch, using a yeoman project and trying out https://github.com/petebacondarwin/dgeni-example and all of them fail with the above exception.

**Comment by petebacondarwin** [comment]
Agh! Let me look into that.

**Comment by petebacondarwin** [comment]
I just cloned the dgeni-example project, ran `npm install` and then `grunt` and the processing executed without failure.

Can you give me some more information about your setup? What version of node are you using?
I am on 4.2.3.

**Comment by r1chardj0n3s** [comment]
Thanks for investigating! I had version 0.10.26 installed. I've just updated to 5.7.0 and the generation works!

**Comment by petebacondarwin** [comment]
Great! Closing then. Open another issue if you have more difficulties.

**Comment by derekmoss** [comment]
Thanks for commenting about the node.js version.

I ran into a similar issue running gulp docs on the angular material source and was getting the exact same error.

upgrading node.js to 4.4 from 0.10 fixed the problem.

**Comment by xenobytezero** [comment]
I am still having this issue with node 5.6, and 6.0.

**Comment by xenobytezero** [comment]
I am still having this issue with NodeJS 6.0.0

After some debugging, it looks like validate.js is not having it's "Promise" parameter set, and its trying to make promises of null. See the "Dependencies" section of the validate.js site - https://validatejs.org/
