### ISSUE TITLE
Document the tool!!

### ISSUE THREAD

**Issue by petebacondarwin** [angular/dgeni#18]
The project should be eating its own dog food by generating its own docs.  This will be a good exercise in the versatility of the tool, since there are some project specific concepts such as packages and processors that would have their own doctypes.

Anyone want to have a go at creating a bike-shed package?

**Comment by daniele-zurico** [comment]
any news regarding documenting the tool? people don't use it because it's like a black box.
Example what are the properties of doc? how to generate a simple navigation bar? It's impossible to do it without a bit of documentation?

**Comment by petebacondarwin** [comment]
Sorry @daniele-zurico - I am completely snowed under right now to do more on docs for dgeni.

**Comment by daniele-zurico** [comment]
@petebacondarwin I'm trying to create a good example for the community but I need more info to do it.
could you give me the information below?
1)the properties of doc...there's a way to printed out the object properties? or a file that describe them?
2)How I can generate a simple navbar for navigate the documentation? I see these:
https://github.com/angular/angular.js/blob/master/docs/app/src/docs.js#L7
https://github.com/angular/angular.js/blob/master/docs/config/templates/nav-data.template.js
but I haven't understood how to use them.
I've a simple github repo:
https://github.com/daniele-zurico/test-dgeni

**Comment by forresst** [comment]
https://github.com/daniele-zurico/test-dgeni/pull/1#

**Comment by petebacondarwin** [comment]
Thanks @forresst

**Comment by JesseChrestler** [comment]
@daniele-zurico 

I created a seed that is mirrored after what the good folks at angular did for their documentation. It's hard to find good samples with good templates to use. You can find it here. https://github.com/JesseChrestler/angular-dgeni-seed

**Comment by Smolations** [comment]
A suggestion two years ago and this issue still hasn't been closed? Good grief...

```
$ npm run docs

> dgeni@0.4.2 docs /Users/thisguy/Workspaces/dgeni
> bin/gen-docs.js ./docs/dgeni-docs.js

info:    running processor: readFilesProcessor
error:   ReferenceError: lineNumber is not defined
    at eval (eval at template (/Users/thisguy/Workspaces/dgeni/node_modules/dgeni-packages/node_modules/lodash/dist/lodash.js:6306:22), <anonymous>:10:10)
    at Function.template (/Users/thisguy/Workspaces/dgeni/node_modules/dgeni-packages/node_modules/lodash/dist/lodash.js:6312:16)
    at Object.getDocs (/Users/thisguy/Workspaces/dgeni/node_modules/dgeni-packages/jsdoc/file-readers/jsdoc.js:20:13)
    at /Users/thisguy/Workspaces/dgeni/node_modules/dgeni-packages/base/processors/read-files.js:73:37
    at _fulfilled (/Users/thisguy/Workspaces/dgeni/node_modules/dgeni-packages/node_modules/q-io/node_modules/q/q.js:798:54)
    at self.promiseDispatch.done (/Users/thisguy/Workspaces/dgeni/node_modules/dgeni-packages/node_modules/q-io/node_modules/q/q.js:827:30)
    at Promise.promise.promiseDispatch (/Users/thisguy/Workspaces/dgeni/node_modules/dgeni-packages/node_modules/q-io/node_modules/q/q.js:760:13)
    at /Users/thisguy/Workspaces/dgeni/node_modules/dgeni-packages/node_modules/q-io/node_modules/q/q.js:574:44
    at flush (/Users/thisguy/Workspaces/dgeni/node_modules/dgeni-packages/node_modules/q-io/node_modules/q/q.js:108:17)
    at doNTCallback0 (node.js:419:9)
```

**Comment by petebacondarwin** [comment]
@Smolations I am not quite sure what the point of your comment is.

**Comment by Smolations** [comment]
@petebacondarwin Sorry, this issue was to generate documentation for the tool itself, which appears to be possible by running `$ npm run docs`, but the command fails with the above error. Is that expected behavior? Is there actually some way to generate documentation for this tool? 

Side note, I encountered a different error while trying to generate docs in the dgeni-packages project with the same command. I was going to post a similar issue there, unless I'm missing something that should solve both problems...

**Comment by petebacondarwin** [comment]
Let me take a quick look!

**Comment by petebacondarwin** [comment]
It seems that we have a problem with the `espree` parser...

**Comment by Smolations** [comment]
Oooohh esprima? Yowsa. Is there any previous tag I could check out with a previous version of that dep, by chance? Doubtful you would know, but just thought I'd ask...

**Comment by petebacondarwin** [comment]
Can't find anything right now...
